<?php

declare(strict_types=1);

namespace RenalTales\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250717104127 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE languages (id INT AUTO_INCREMENT NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, code VARCHAR(10) NOT NULL, name VARCHAR(100) NOT NULL, nativeName VARCHAR(100) NOT NULL, active TINYINT(1) NOT NULL, isDefault TINYINT(1) NOT NULL, direction VARCHAR(3) DEFAULT NULL, region VARCHAR(5) DEFAULT NULL, sortOrder INT NOT NULL, INDEX languages_active_idx (active), UNIQUE INDEX languages_code_unique (code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE audit_logs DROP FOREIGN KEY fk_audit_logs_user_id');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_1');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_2');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_3');
        $this->addSql('ALTER TABLE email_verifications DROP FOREIGN KEY email_verifications_ibfk_1');
        $this->addSql('ALTER TABLE email_verifications_new DROP FOREIGN KEY fk_email_verifications_user_id');
        $this->addSql('ALTER TABLE failed_login_attempts DROP FOREIGN KEY failed_login_attempts_ibfk_1');
        $this->addSql('ALTER TABLE language_preferences DROP FOREIGN KEY fk_language_preferences_user_id');
        $this->addSql('ALTER TABLE login_logs DROP FOREIGN KEY login_logs_ibfk_1');
        $this->addSql('ALTER TABLE logout_logs DROP FOREIGN KEY logout_logs_ibfk_1');
        $this->addSql('ALTER TABLE password_resets_new DROP FOREIGN KEY fk_password_resets_user_id');
        $this->addSql('ALTER TABLE security_events DROP FOREIGN KEY fk_security_events_user_id');
        $this->addSql('ALTER TABLE stories DROP FOREIGN KEY stories_ibfk_1');
        $this->addSql('ALTER TABLE stories DROP FOREIGN KEY stories_ibfk_2');
        $this->addSql('ALTER TABLE story_contents DROP FOREIGN KEY story_contents_ibfk_1');
        $this->addSql('ALTER TABLE story_contents DROP FOREIGN KEY story_contents_ibfk_2');
        $this->addSql('ALTER TABLE story_revisions DROP FOREIGN KEY story_revisions_ibfk_1');
        $this->addSql('ALTER TABLE story_revisions DROP FOREIGN KEY story_revisions_ibfk_2');
        $this->addSql('ALTER TABLE user_activity_logs DROP FOREIGN KEY user_activity_logs_ibfk_1');
        $this->addSql('ALTER TABLE user_profiles DROP FOREIGN KEY fk_user_profiles_user_id');
        $this->addSql('ALTER TABLE user_registration_logs DROP FOREIGN KEY user_registration_logs_ibfk_1');
        $this->addSql('ALTER TABLE user_sessions DROP FOREIGN KEY user_sessions_ibfk_1');
        $this->addSql('ALTER TABLE user_sessions_new DROP FOREIGN KEY fk_user_sessions_user_id');
        $this->addSql('DROP TABLE activity_logs');
        $this->addSql('DROP TABLE audit_logs');
        $this->addSql('DROP TABLE comments');
        $this->addSql('DROP TABLE database_migrations');
        $this->addSql('DROP TABLE email_verifications');
        $this->addSql('DROP TABLE email_verifications_new');
        $this->addSql('DROP TABLE failed_login_attempts');
        $this->addSql('DROP TABLE language_preferences');
        $this->addSql('DROP TABLE login_attempts');
        $this->addSql('DROP TABLE login_logs');
        $this->addSql('DROP TABLE logout_logs');
        $this->addSql('DROP TABLE migrations');
        $this->addSql('DROP TABLE password_resets');
        $this->addSql('DROP TABLE password_resets_new');
        $this->addSql('DROP TABLE rate_limits');
        $this->addSql('DROP TABLE security_events');
        $this->addSql('DROP TABLE security_logs');
        $this->addSql('DROP TABLE stories');
        $this->addSql('DROP TABLE story_categories');
        $this->addSql('DROP TABLE story_contents');
        $this->addSql('DROP TABLE story_revisions');
        $this->addSql('DROP TABLE system_logs');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE users_new');
        $this->addSql('DROP TABLE user_activity_logs');
        $this->addSql('DROP TABLE user_profiles');
        $this->addSql('DROP TABLE user_registration_logs');
        $this->addSql('DROP TABLE user_sessions');
        $this->addSql('DROP TABLE user_sessions_new');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity_logs (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, action VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_user_id (user_id), INDEX idx_action (action), INDEX idx_created_at (created_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED DEFAULT NULL, event_type VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, event_category ENUM(\'auth\', \'user\', \'security\', \'system\', \'data\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, resource_type VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, resource_id INT UNSIGNED DEFAULT NULL, old_values JSON DEFAULT NULL, new_values JSON DEFAULT NULL, ip_address VARCHAR(45) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, user_agent VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, session_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, request_method VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, request_url VARCHAR(2000) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, severity ENUM(\'info\', \'warning\', \'error\', \'critical\') CHARACTER SET utf8mb4 DEFAULT \'info\' COLLATE `utf8mb4_unicode_ci`, additional_data JSON DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_event_category (event_category), INDEX idx_security_events (event_category, severity, created_at), INDEX idx_user_events (user_id, event_type, created_at), INDEX idx_ip_address (ip_address), INDEX idx_resource (resource_type, resource_id), INDEX idx_user_id (user_id), INDEX idx_created_at (created_at), INDEX idx_event_type (event_type), INDEX idx_session_id (session_id), INDEX idx_severity (severity), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE comments (id INT UNSIGNED AUTO_INCREMENT NOT NULL, story_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED NOT NULL, parent_id INT UNSIGNED DEFAULT NULL, content TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, status ENUM(\'pending\', \'approved\', \'rejected\') CHARACTER SET utf8mb4 DEFAULT \'pending\' NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX parent_id (parent_id), INDEX idx_status (status), INDEX story_id (story_id), INDEX user_id (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE database_migrations (id INT UNSIGNED AUTO_INCREMENT NOT NULL, migration VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, batch INT UNSIGNED NOT NULL, executed_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX uk_migration (migration), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE email_verifications (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, token VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX user_id (user_id), INDEX idx_token (token), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE email_verifications_new (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, token_hash VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, expires_at DATETIME NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, verified_at DATETIME DEFAULT NULL, ip_address VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, user_agent VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, is_verified TINYINT(1) DEFAULT 0, verification_type ENUM(\'registration\', \'email_change\', \'login_verification\') CHARACTER SET utf8mb4 DEFAULT \'registration\' COLLATE `utf8mb4_unicode_ci`, old_email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX idx_created_at (created_at), INDEX idx_expires_at (expires_at), UNIQUE INDEX uk_token_hash (token_hash), INDEX idx_cleanup (expires_at, is_verified), INDEX idx_is_verified (is_verified), INDEX idx_user_id (user_id), INDEX idx_verification_type (verification_type), INDEX idx_email (email), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE failed_login_attempts (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED DEFAULT NULL, username_or_email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, ip_address VARCHAR(45) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, user_agent TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, country VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, city VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, failure_reason ENUM(\'invalid_credentials\', \'account_suspended\', \'account_inactive\', \'too_many_attempts\', \'user_not_found\', \'email_not_verified\', \'other\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, attempted_password_hash VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, request_method VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'POST\' COLLATE `utf8mb4_unicode_ci`, request_url TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, session_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, attempt_count INT UNSIGNED DEFAULT 1, is_blocked TINYINT(1) DEFAULT 0, blocked_until DATETIME DEFAULT NULL, threat_level ENUM(\'low\', \'medium\', \'high\', \'critical\') CHARACTER SET utf8mb4 DEFAULT \'medium\' COLLATE `utf8mb4_unicode_ci`, additional_data JSON DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_user_attempts (user_id, created_at), INDEX idx_created_at (created_at), INDEX idx_is_blocked (is_blocked), INDEX idx_username_or_email (username_or_email), INDEX idx_threat_analysis (threat_level, failure_reason, created_at), INDEX idx_ip_attempts (ip_address, created_at), INDEX idx_blocked_until (blocked_until), INDEX idx_ip_address (ip_address), INDEX idx_active_blocks (is_blocked, blocked_until), INDEX idx_threat_level (threat_level), INDEX idx_failure_reason (failure_reason), INDEX idx_user_id (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE language_preferences (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, language_code VARCHAR(10) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, is_primary TINYINT(1) DEFAULT 0, proficiency_level ENUM(\'beginner\', \'intermediate\', \'advanced\', \'native\') CHARACTER SET utf8mb4 DEFAULT \'intermediate\' COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX uk_user_language (user_id, language_code), INDEX idx_is_primary (is_primary), INDEX idx_user_id (user_id), INDEX idx_language_code (language_code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE login_attempts (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, success TINYINT(1) DEFAULT 0, ip_address VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, user_agent TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_identifier (identifier), INDEX idx_created_at (created_at), INDEX idx_ip_address (ip_address), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE login_logs (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, username VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, login_time DATETIME DEFAULT CURRENT_TIMESTAMP, ip_address VARCHAR(45) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, user_agent TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, country VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, city VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, login_source VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'web\' COLLATE `utf8mb4_unicode_ci`, additional_data JSON DEFAULT NULL, INDEX idx_login_time (login_time), INDEX idx_user_id (user_id), INDEX idx_login_source (login_source), INDEX idx_username (username), INDEX idx_ip_address (ip_address), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE logout_logs (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, username VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, logout_time DATETIME DEFAULT CURRENT_TIMESTAMP, ip_address VARCHAR(45) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, user_agent TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, country VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, city VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, logout_source VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'web\' COLLATE `utf8mb4_unicode_ci`, additional_data JSON DEFAULT NULL, INDEX idx_ip_address (ip_address), INDEX idx_logout_time (logout_time), INDEX idx_user_id (user_id), INDEX idx_logout_source (logout_source), INDEX idx_username (username), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE migrations (id INT AUTO_INCREMENT NOT NULL, version VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, executed_at DATETIME NOT NULL, UNIQUE INDEX unique_version (version), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE password_resets (email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, token VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_email (email)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE password_resets_new (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, token_hash VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, expires_at DATETIME NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, used_at DATETIME DEFAULT NULL, ip_address VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, user_agent VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, is_used TINYINT(1) DEFAULT 0, INDEX idx_is_used (is_used), UNIQUE INDEX uk_token_hash (token_hash), INDEX idx_created_at (created_at), INDEX idx_user_id (user_id), INDEX idx_cleanup (expires_at, is_used), INDEX idx_expires_at (expires_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE rate_limits (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at INT NOT NULL, INDEX idx_created_at (created_at), INDEX idx_identifier (identifier), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE security_events (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED DEFAULT NULL, event_type ENUM(\'login_success\', \'login_failure\', \'logout\', \'password_change\', \'email_change\', \'account_locked\', \'account_unlocked\', \'suspicious_activity\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, ip_address VARCHAR(45) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, user_agent VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, country VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, city VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, risk_score TINYINT(1) DEFAULT 0, failure_reason VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, attempt_count INT UNSIGNED DEFAULT 1, blocked_until DATETIME DEFAULT NULL, additional_data JSON DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_user_id (user_id), INDEX idx_created_at (created_at), INDEX idx_event_type (event_type), INDEX idx_blocked_until (blocked_until), INDEX idx_ip_address (ip_address), INDEX idx_security_analysis (event_type, risk_score, created_at), INDEX idx_user_events (user_id, event_type, created_at), INDEX idx_risk_score (risk_score), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE security_logs (id INT AUTO_INCREMENT NOT NULL, event VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, data JSON DEFAULT NULL, ip_address VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, user_agent TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_ip_address (ip_address), INDEX idx_created_at (created_at), INDEX idx_event (event), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE stories (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, category_id INT UNSIGNED NOT NULL, original_language CHAR(2) CHARACTER SET utf8mb4 DEFAULT \'en\' NOT NULL COLLATE `utf8mb4_unicode_ci`, status ENUM(\'draft\', \'pending_review\', \'published\', \'rejected\') CHARACTER SET utf8mb4 DEFAULT \'draft\' NOT NULL COLLATE `utf8mb4_unicode_ci`, access_level ENUM(\'public\', \'registered\', \'verified\', \'premium\') CHARACTER SET utf8mb4 DEFAULT \'public\' NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, published_at DATETIME DEFAULT NULL, INDEX idx_status (status), INDEX idx_access_level (access_level), INDEX user_id (user_id), INDEX idx_published_at (published_at), INDEX category_id (category_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE story_categories (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, slug VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_slug (slug), UNIQUE INDEX slug (slug), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE story_contents (id INT UNSIGNED AUTO_INCREMENT NOT NULL, story_id INT UNSIGNED NOT NULL, language CHAR(2) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, title VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, content TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, excerpt TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, meta_description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, translator_id INT UNSIGNED DEFAULT NULL, status ENUM(\'draft\', \'pending_review\', \'published\', \'rejected\') CHARACTER SET utf8mb4 DEFAULT \'draft\' NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX translator_id (translator_id), INDEX idx_language (language), UNIQUE INDEX unique_story_language (story_id, language), INDEX idx_status (status), INDEX IDX_B71F0FEBAA5D4036 (story_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE story_revisions (id INT UNSIGNED AUTO_INCREMENT NOT NULL, story_content_id INT UNSIGNED NOT NULL, editor_id INT UNSIGNED NOT NULL, title VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, content TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, excerpt TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, meta_description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, revision_notes TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX story_content_id (story_content_id), INDEX editor_id (editor_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE system_logs (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, level ENUM(\'debug\', \'info\', \'notice\', \'warning\', \'error\', \'critical\', \'alert\', \'emergency\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, message TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, context JSON DEFAULT NULL, channel VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'system\' COLLATE `utf8mb4_unicode_ci`, extra JSON DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_level_created (level, created_at), INDEX idx_level (level), INDEX idx_channel (channel), INDEX idx_created_at (created_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT NOT NULL, username VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, password_hash VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, full_name VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, role ENUM(\'user\', \'verified_user\', \'translator\', \'moderator\', \'admin\') CHARACTER SET utf8mb4 DEFAULT \'user\' NOT NULL COLLATE `utf8mb4_unicode_ci`, two_factor_secret VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, two_factor_enabled TINYINT(1) DEFAULT 0 NOT NULL, language_preference CHAR(2) CHARACTER SET utf8mb4 DEFAULT \'en\' NOT NULL COLLATE `utf8mb4_unicode_ci`, email_verified_at DATETIME DEFAULT NULL, remember_token VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, last_login_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_email_verified (email_verified_at), UNIQUE INDEX username (username), UNIQUE INDEX email (email), INDEX idx_role (role), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE users_new (id INT UNSIGNED AUTO_INCREMENT NOT NULL, username VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, password_hash VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, email_verified TINYINT(1) DEFAULT 0, email_verified_at DATETIME DEFAULT NULL, status ENUM(\'active\', \'inactive\', \'suspended\') CHARACTER SET utf8mb4 DEFAULT \'active\' COLLATE `utf8mb4_unicode_ci`, last_login_at DATETIME DEFAULT NULL, failed_login_count INT UNSIGNED DEFAULT 0, locked_until DATETIME DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_created_at (created_at), INDEX idx_email_verified (email_verified), UNIQUE INDEX email (email), INDEX idx_locked_until (locked_until), INDEX idx_status (status), UNIQUE INDEX uk_username (username), INDEX idx_last_login (last_login_at), UNIQUE INDEX uk_email (email), UNIQUE INDEX username (username), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_activity_logs (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, username VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, action_type VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, action_description TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, resource_type VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, resource_id INT UNSIGNED DEFAULT NULL, old_values JSON DEFAULT NULL, new_values JSON DEFAULT NULL, ip_address VARCHAR(45) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, user_agent TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, country VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, city VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, request_method VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, request_url TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, session_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, severity ENUM(\'low\', \'medium\', \'high\', \'critical\') CHARACTER SET utf8mb4 DEFAULT \'medium\' COLLATE `utf8mb4_unicode_ci`, additional_data JSON DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_user_id (user_id), INDEX idx_created_at (created_at), INDEX idx_resource_id (resource_id), INDEX idx_username (username), INDEX idx_session_id (session_id), INDEX idx_ip_address (ip_address), INDEX idx_action_type (action_type), INDEX idx_critical_actions (severity, action_type, created_at), INDEX idx_user_actions (user_id, action_type, created_at), INDEX idx_severity (severity), INDEX idx_resource_type (resource_type), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_profiles (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, first_name VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, last_name VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, display_name VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, avatar_url VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, bio TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, timezone VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'UTC\' COLLATE `utf8mb4_unicode_ci`, language VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'en\' COLLATE `utf8mb4_unicode_ci`, date_format VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'Y-m-d\' COLLATE `utf8mb4_unicode_ci`, time_format VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'H:i\' COLLATE `utf8mb4_unicode_ci`, phone VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_of_birth DATE DEFAULT NULL, gender ENUM(\'male\', \'female\', \'other\', \'prefer_not_to_say\') CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, country VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, city VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, privacy_settings JSON DEFAULT NULL, notification_settings JSON DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_language (language), INDEX idx_country (country), UNIQUE INDEX uk_user_id (user_id), INDEX idx_created_at (created_at), INDEX idx_display_name (display_name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_registration_logs (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED DEFAULT NULL, username VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, registration_status ENUM(\'success\', \'failed\', \'pending\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, failure_reason VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ip_address VARCHAR(45) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, user_agent TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, country VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, city VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, registration_source VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'web\' COLLATE `utf8mb4_unicode_ci`, referrer TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, additional_data JSON DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_failed_registrations (registration_status, ip_address, created_at), INDEX idx_registration_status (registration_status), INDEX idx_user_id (user_id), INDEX idx_created_at (created_at), INDEX idx_email (email), INDEX idx_registration_source (registration_source), INDEX idx_ip_address (ip_address), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_sessions (id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, user_id INT UNSIGNED NOT NULL, ip_address VARCHAR(45) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, user_agent VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, payload TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, last_activity INT UNSIGNED NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX user_id (user_id), INDEX idx_last_activity (last_activity), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_sessions_new (id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, user_id INT UNSIGNED DEFAULT NULL, ip_address VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, user_agent VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, payload LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, last_activity DATETIME DEFAULT CURRENT_TIMESTAMP, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME DEFAULT NULL, INDEX idx_expires_at (expires_at), INDEX idx_cleanup (expires_at, last_activity), INDEX idx_user_id (user_id), INDEX idx_last_activity (last_activity), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT fk_audit_logs_user_id FOREIGN KEY (user_id) REFERENCES users_new (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT comments_ibfk_1 FOREIGN KEY (story_id) REFERENCES stories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT comments_ibfk_2 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT comments_ibfk_3 FOREIGN KEY (parent_id) REFERENCES comments (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE email_verifications ADD CONSTRAINT email_verifications_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE email_verifications_new ADD CONSTRAINT fk_email_verifications_user_id FOREIGN KEY (user_id) REFERENCES users_new (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE failed_login_attempts ADD CONSTRAINT failed_login_attempts_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE language_preferences ADD CONSTRAINT fk_language_preferences_user_id FOREIGN KEY (user_id) REFERENCES users_new (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE login_logs ADD CONSTRAINT login_logs_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE logout_logs ADD CONSTRAINT logout_logs_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE password_resets_new ADD CONSTRAINT fk_password_resets_user_id FOREIGN KEY (user_id) REFERENCES users_new (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE security_events ADD CONSTRAINT fk_security_events_user_id FOREIGN KEY (user_id) REFERENCES users_new (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE stories ADD CONSTRAINT stories_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stories ADD CONSTRAINT stories_ibfk_2 FOREIGN KEY (category_id) REFERENCES story_categories (id)');
        $this->addSql('ALTER TABLE story_contents ADD CONSTRAINT story_contents_ibfk_1 FOREIGN KEY (story_id) REFERENCES stories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE story_contents ADD CONSTRAINT story_contents_ibfk_2 FOREIGN KEY (translator_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE story_revisions ADD CONSTRAINT story_revisions_ibfk_1 FOREIGN KEY (story_content_id) REFERENCES story_contents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE story_revisions ADD CONSTRAINT story_revisions_ibfk_2 FOREIGN KEY (editor_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE user_activity_logs ADD CONSTRAINT user_activity_logs_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_profiles ADD CONSTRAINT fk_user_profiles_user_id FOREIGN KEY (user_id) REFERENCES users_new (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_registration_logs ADD CONSTRAINT user_registration_logs_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_sessions ADD CONSTRAINT user_sessions_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_sessions_new ADD CONSTRAINT fk_user_sessions_user_id FOREIGN KEY (user_id) REFERENCES users_new (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP TABLE languages');
    }
}
